name: Docker Image CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: Init submodule
      run: git submodule update --init
    - name: Stack Setup
      uses: mstksg/setup-stack@v1
    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
          ${{ runner.os }}-stack-
    - name: Cache .stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: ${{ runner.os }}-work-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-work-${{ hashFiles('stack.yaml.lock') }}
          ${{ runner.os }}-work-
    - name: stack build
      run: stack update && stack setup && stack build
    - name: Copy Built Binary
      run: mkdir ./out && mv $(stack path --local-install-root)/bin/* ./out/
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmconner/kuisthesis-builder
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
