name: Docker Image CI

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: Init submodule
      run: git submodule update --init
    - name: Stack Setup
      uses: mstksg/setup-stack@v1
    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('pandoc/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('pandoc/stack.yaml.lock') }}
          ${{ runner.os }}-stack-
    - name: Cache .stack-work
      uses: actions/cache@v1
      with:
        path: pandoc/.stack-work
        key: ${{ runner.os }}-work-${{ hashFiles('pandoc/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-work-${{ hashFiles('pandoc/stack.yaml.lock') }}
          ${{ runner.os }}-work-
    - name: stack build
      run: stack update && stack setup && stack build
      working-directory: pandoc
    - name: Copy Built Binary
      run: mkdir ../out && mv $(stack path --local-install-root)/bin/* ../out/
      working-directory: ./pandoc
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmconner/kuisthesis-builder
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
